[engine]
rate = 200                                   # 速率
duration = "20s"                           # 持续时间
cap = 2000                                    # 客户端虚拟机数量
tpsunit= "5s"                                 #计算tps的单位时间

[client]
script = "benchmark/fabricExample/script.lua"  # 脚本
type = "fabric"                          # 区块链类型
config = "benchmark/fabricExample/fabric"  # 区块链SDK配置路径
contract = "github.com/meshplus/hyperbench/benchmark/fabricExample/contract"   # 合约目录路径
args = ["init", "A", "123", "B", "234"]                               # 合约参数路径

[client.options]
channel = "mychannel"
initArgs = ["init", "A", "123", "B", "234"]
MSP = true
instant = 1
